### ISSUE TITLE
Question about the process flow for WPE

### ISSUE THREAD

**Issue by kamo-naoyuki** [desh2608/gss#29]
I have a question about the process flow for WPE.

I'm not sure that my understandings are correct, but in the this code, the processed signal by WPE is input for gss, but it's not fed into beamformer. 

https://github.com/desh2608/gss/blob/0d2cae4c16d4ffa4410a9be1d5134d3f82ac5ca1/gss/core/enhancer.py#L313

https://github.com/desh2608/gss/blob/0d2cae4c16d4ffa4410a9be1d5134d3f82ac5ca1/gss/core/enhancer.py#L316

https://github.com/desh2608/gss/blob/0d2cae4c16d4ffa4410a9be1d5134d3f82ac5ca1/gss/core/enhancer.py#L344-L349

I checked the original code: https://github.com/fgnt/pb_chime5/blob/master/pb_chime5/core.py#L522-L564  and the paper, but in the code, the WPE signal seems also used for beamformer.

I guess this is a bug caused by implementation of chunk process.

**Comment by desh2608** [comment]
Ahh, good catch! I'll create a PR to fix this. I wonder how much impact this would have on the downstream performance.

**Comment by desh2608** [comment]
Fixed in #31.
