### ISSUE TITLE
Remove lhotse @ git+http://github.com/lhotse-speech/lhotse

### ISSUE THREAD

**Issue by boeddeker** [desh2608/gss#32]
Could you remove the git dependency for lhotse in the setup.py or does this package need non-published parts of lhotse?
Recent pip versions have the "feature", that git dependencies always overwrite the installed version, independent if it is a PyPI, a git or a user installation.

**Comment by pzelasko** [comment]
@desh2608 if you need some unreleased lhotse features to pin a PyPI version I can make a new release.

**Comment by desh2608** [comment]
I think the latest Lhotse should be fine. Will make this change.

**Comment by boeddeker** [comment]
Thank you.
