### ISSUE TITLE
Chunking along time frames to save GPU Ram? Why not along frequency dim?

### ISSUE THREAD

**Issue by boeddeker** [desh2608/gss#33]
I saw the chunking in the code:

https://github.com/desh2608/gss/blob/ff0627511eefce04b910afe46b7606d9b7f5af3a/gss/core/enhancer.py#L301-L313

Assuming you followed our convention, then `T` means time frame, and when I read the code correct, then you do a chunking along the time frames. This is suboptimal and in my mind there is a much better option: WPE, GSS and beamforming is done for each frequency independently, i.e. only one frequency is considered, while the others are ignored for the particular frequency.
When you do the chunking along the frequency dimension, the result would be the same.

**Comment by desh2608** [comment]
The chunking is only performed as a fallback option. Users are not expected to rely on it unless the segments are too long or there are a very large number of channels. If you are getting a lot of OOMs, I recommend reducing the batch size instead.

**Comment by boeddeker** [comment]
I just investigated, why it was so slow on our HPC system (not enough CPUs allocated) and found this in the code.
I am not sure, if my performance will degenerate for CHiME-7, since I have only 40 GB GPUs and not the required 48 GB GPUs as it was mentioned in the CHiME7 Slack channel.

Today someone reported in the CHiME-7 Slack channel, that he has issues with 10 GB GPUs, when chunking is used.
This might be the problem.

**Comment by desh2608** [comment]
For a reasonably large number of channels (e.g. 24 for CHiME), I have been able to enhance using 24G GPUs. DiPCo may be an issue since it has 35 channels. I haven't tried enhancing it personally, but @popcornell has successfully done it on 40G GPUs.

**Comment by desh2608** [comment]
That said, I am open to reviewing a PR to change the chunking behavior if someone wants to implement it along frequency dim.

**Comment by boeddeker** [comment]
OK, I will prepare a PR.
