### ISSUE TITLE
Disable of segment-batching

### ISSUE THREAD

**Issue by ybNo1** [desh2608/gss#42]
Thank you for your work! I would like to ask that in the paper, it is mentioned that segment-batching is not enabled on CHiME-7, but I cannot find the disabling option in the code. In addition, if segment-batching is disabled, does that mean each cut needs to be concatenated with context, thereby resulting in a significant increase in inference time?

**Comment by desh2608** [comment]
In the CHiME-6 recipe (https://github.com/desh2608/gss/blob/a6b2e1f59d1bddcd2e37b517ceabf4970892685d/recipes/chime6/run.sh#L69), we set `--max-batch-cuts 1` which, in effect, disables the segment batching. Adding context etc. is done by default regardless of whether or not you use segment batching. There would be some increase in inference time dur to this, but I don't think it's very large.

**Comment by ybNo1** [comment]
> In the CHiME-6 recipe (https://github.com/desh2608/gss/blob/a6b2e1f59d1bddcd2e37b517ceabf4970892685d/recipes/chime6/run.sh#L69), we set `--max-batch-cuts 1` which, in effect, disables the segment batching. Adding context etc. is done by default regardless of whether or not you use segment batching. There would be some increase in inference time dur to this, but I don't think it's very large.

Got it! Thanks for your reply!
